# Generated by Django 6.0.2 on 2026-02-09 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('skracenica', models.CharField(max_length=3)),
                ('grad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilKorisnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('tip_korisnika', models.CharField(choices=[('admin', 'Administrator'), ('radnik', 'Radnik'), ('putnik', 'Putnik')], default='putnik', max_length=20)),
                ('uloga', models.CharField(choices=[('admin', 'Administrator'), ('radnik', 'Radnik'), ('putnik', 'Putnik')], default='putnik', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Let',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacija', models.CharField(max_length=100)),
                ('vreme_polaska', models.DateTimeField()),
                ('aviokompanija', models.CharField(default='Air Serbia', max_length=100)),
                ('odrediste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odrediste_letovi', to='core.aerodrom')),
                ('polaziste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polaziste_letovi', to='core.aerodrom')),
            ],
        ),
        migrations.CreateModel(
            name='AvioPonuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('klasa', models.CharField(default='Ekonomska', max_length=50)),
                ('let', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.let')),
            ],
        ),
        migrations.CreateModel(
            name='PracenjeCena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_cene', models.DecimalField(decimal_places=2, max_digits=10)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('let', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.let')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervacija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateTimeField(auto_now_add=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ponuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.avioponuda')),
            ],
        ),
        migrations.CreateModel(
            name='ZakljucavanjePonude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('je_zakljucano', models.BooleanField(default=False)),
                ('datum_vreme', models.DateTimeField(auto_now_add=True)),
                ('avio_ponuda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.avioponuda')),
            ],
        ),
    ]
