# Generated by Django 6.0.2 on 2026-02-08 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerodrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=255)),
                ('skracenica', models.CharField(max_length=3)),
                ('grad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilKorisnika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uloga', models.CharField(choices=[('admin', 'Administrator'), ('radnik', 'Radnik'), ('putnik', 'Putnik')], default='putnik', max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('korisnik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
