# Generated by Django 6.0.2 on 2026-02-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profilkorisnika_korisnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='let',
            name='aviokompanija',
            field=models.CharField(default='Air Serbia', max_length=200),
        ),
    ]
