# Generated by Django 5.0.1 on 2026-03-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_let_aviokompanija'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerodrom',
            name='latituda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='aerodrom',
            name='longituda',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
